{{- if .Values.windmill.workers.tools.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goat.serviceFullname" (dict "context" . "component" "windmill-worker-tools") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "goat.serviceLabels" (dict "context" . "component" "windmill-worker-tools") | nindent 4 }}
data:
  {{- range $k, $v := .Values.windmill.workers.tools.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- if and (include "goat.caBundle.enabled" .) (not (include "goat.env.userSet" (dict "values" .Values.windmill.workers.tools "key" "GOAT_CA_BUNDLE"))) }}
  GOAT_CA_BUNDLE: {{ include "goat.caBundle.path" . | quote }}
  {{- end }}
{{- end }}
